# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
- task: AzureCLI@1
  inputs:
    azureSubscription: 'CSE Dev Crews Americas West (7060bca0-7a3c-44bd-b54c-4bb1e9facfac)'
    scriptLocation: 'inlineScript'
    inlineScript: 'az acr login --name heliumintacr'
- script: |
    docker build --target=release -t heliumintacr.azurecr.io/helium:canary .
    docker push heliumintacr.azurecr.io/helium:canary
  displayName: 'dockerize and push to ACR'
- script: |
    sleep 2m
    docker build --build-arg integration_server_url=https://heliumint.azurewebsites.net --target=integration -t  testhelium:canary .
    docker run -i -p 3000:3000 testhelium:canary
  displayName: 'sleep 2m & then build integration tests and test'
